### ISSUE TITLE
Avoid targeting specific IDs in your JS

### ISSUE THREAD

**Issue by mandiwise** [redacademy/funds-fall-2016#13]
This code is a bit fragile because it depends on that menu item always having that ID:

```
$('#menu-item-44').on('click', ...
```

Consider showing custom classes on your menu items, and targeting your click event at that instead:

<img width="975" alt="screenshot" src="https://cloud.githubusercontent.com/assets/1518780/21029787/455ce8b6-bd50-11e6-83c5-6fc5a97d53b0.png">

**Comment by MartinZ29** [comment]
Deleted.... This is a try to access the default function of submenu in wordpress. Failed, and luckily we removed submenu. Forgot to delete code. I will clear it right now...Thanks !!!
