### ISSUE TITLE
Consider placing login page CSS in external stylesheet

### ISSUE THREAD

**Issue by mandiwise** [redacademy/funds-fall-2016#3]
You have a lot of CSS in this function:

https://github.com/redacademy/funds-fall-2016/blob/master/themes/renewal-funds/inc/extras.php#L175

I would recommend placing it in a separate stylesheet and enqueuing the stylesheet in that function instead (separation of concerns FTW!).

**Comment by chk91** [comment]
Moved style to a different css file. Tested on local but seems to have a problem on staging site.
