### ISSUE TITLE
SVG icons in your media library?

### ISSUE THREAD

**Issue by mandiwise** [redacademy/funds-fall-2016#8]
There are a number of SVG icons uploaded to the media library...WP does not support SVGs in the media library out-of-the-box (and for a good reason), plus these seem like the kinds of things that should be theme images anyway.

Please remove if they are not needed.

**Comment by MartinZ29** [comment]
i got a plugin named menu icon, and it only accepts svg. so when i uploaded those icons through the plugin, they went to media library. I can delete some of icons i didn't use right now.
